apiVersion: apps/v1
kind: Deployment
metadata:
  name: acctInfo
  labels:
    app: acctInfo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acctInfo
  template:
    metadata:
      labels:
        app: acctInfo
    spec:
      containers:
        - name: acctInfo
          image: username/acctInfo:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5